### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by mauvm** [kukua/concava-connector-spul#1]
Make logging more consistent and log device ID as hex string.

**Comment by GabrielNotman** [comment]
I pushed some changes to connector.go which now
show the device ID in hex for both console and log output.

On 24 December 2015 at 13:29, Maurits van Mastrigt <notifications@github.com

> wrote:
> 
> Make logging more consistent and log device ID as hex string.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kukua/concava-spul-connector/issues/1.

## 

Regards,

Gabriel Notman

Software Developer at SODAQ

If our environment could speak, what would it say?

Start connecting devices everywhere.

www.sodaq.com
